version: '3.8'

services:
  mysqlbus:
    image: mysql:8
    container_name: bus-ticket-booking-db
    environment:
      MYSQL_DATABASE: test
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3326:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    container_name: bus-ticket-booking-mailhog
    ports:
      - "8026:8025"   # Web UI
      - "1026:1025"   # SMTP port

  app:
    build: .
    container_name: bus-ticket-booking-app
    depends_on:
      - mysqlbus
      - mailhog
    ports:
      - "8082:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqlbus:3306/test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_MAIL_HOST: mailhog
      SPRING_MAIL_PORT: 1025
    restart: on-failure

  nginx:
    image: nginx:latest
    container_name: bus-ticket-booking-nginx
    ports:
      - "8070:80"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
volumes:
  mysql_data: